language: go
sudo: false
go:
  - 1.9

env:
  global:
    - TFLIB=libtensorflow-cpu-linux-x86_64-1.6.0.tar.gz
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/lib

before_install:
  - mkdir -p $TRAVIS_BUILD_DIR/lib
  - wget https://storage.googleapis.com/tensorflow/libtensorflow/$TFLIB
  - tar xfz $TFLIB
  - go get github.com/tensorflow/tensorflow/tensorflow/go
  - go get github.com/tensorflow/tensorflow/tensorflow/go/op
  - git clone https://github.com/google/protobuf.git
  - cd protobuf
  - ./autogen.sh
  - ./configure --prefix=$TRAVIS_BUILD_DIR
  - make && make install
  - go get -u github.com/golang/protobuf/protoc-gen-go

install:
  - go get github.com/dmwm/cmsauth
  - go get github.com/vkuznet/x509proxy
  - go get github.com/shirou/gopsutil
  - go get github.com/sirupsen/logrus
